### ISSUE TITLE
not issue, suggestion? :)

### ISSUE THREAD

**Issue by y0d4a** [gentilkiwi/kekeo#5]
what do you think, can this be helpful? :)
https://github.com/programa-stic/security-advisories/tree/master/ObjSys/CVE-2016-5080

**Comment by gentilkiwi** [comment]
Hello y0d4a,

I use OSS ASN.1 stack ( http://www.oss.com/asn1/products/asn1-c/asn1-c.html ) not Objective Systems one.
As far I know, Microsoft Kerberos stack uses OSS ASN.1 too (it was a little because of that I choose OSS ASN.1 too)

So I don't think I can use this CVE against a Kerberos system (neither MIT or Heimdal...)

**Comment by y0d4a** [comment]
aha my bad, thank you on your explanation ;)
